#!/data/data/com.termux/files/usr/bin/bash

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"

VERSION="1.0.0"

# Load modules
source "$BASE_DIR/modules/security.sh"
source "$BASE_DIR/modules/firewall.sh"
source "$BASE_DIR/modules/hash.sh"
source "$BASE_DIR/modules/encrypt.sh"


logo(){

echo -e "\033[96m
██████╗ ██╗██╗   ██╗██╗███╗   ██╗██╗████████╗██╗   ██╗
██╔══██╗██║██║   ██║██║████╗  ██║██║╚══██╔══╝╚██╗ ██╔╝
██║  ██║██║██║   ██║██║██╔██╗ ██║██║   ██║    ╚████╔╝
██║  ██║██║╚██╗ ██╔╝██║██║╚██╗██║██║   ██║     ╚██╔╝
██████╔╝██║ ╚████╔╝ ██║██║ ╚████║██║   ██║      ██║
╚═════╝ ╚═╝  ╚═══╝  ╚═╝╚═╝  ╚═══╝╚═╝   ╚═╝      ╚═╝
\033[0m"

echo -e "\033[95mCODE FIRST • SECURITY ALWAYS • IMPACT FOREVER\033[0m"

}


logo


case "$1" in


--version)

echo "Divinity CLI v$VERSION"
;;


security)

if [ "$2" = "scan" ]; then
security_scan
fi

;;


firewall)

firewall_check

;;


hash)

hash_check

;;


encrypt)

encrypt_file "$2"

;;


report)

generate_report

;;


*)

echo "Divinity Commands:"
echo ""
echo "divinity security scan"
echo "divinity firewall"
echo "divinity hash"
echo "divinity encrypt"
echo "divinity report"

;;

esac
